### ISSUE TITLE
 application question of URDF import 

### ISSUE THREAD

**Issue by ningmimg** [olmerg/rtb_serial_robot#5]
When I run planar_3dof/example.py in PyCharm,  the browser report an error with the message "Application error: a client-side exception has occurred (see the browser console for more information). content in the console is displayed as 

Failed to load resource: the server responded with a status of 404 (File not found)
:52000/retrieve/C:/Users/ningtianze/Desktop/rtb_serial_robot-main/rtb_serial_robot-main/planar_3dof/xacro/lesson_urdf/meshes/visual/gripper.stl:1 
        
        
        Failed to load resource: the server responded with a status of 404 (File not found)
2index-0723cc3b940b78c7.js:194  Error: Could not load retrieve/C:\Users\ningtianze\Desktop\rtb_serial_robot-main\rtb_serial_robot-main\planar_3dof\xacro\lesson_urdf\meshes\visual\arm_link.stl: fetch for "http://localhost:52000/retrieve/C:/Users/ningtianze/Desktop/rtb_serial_robot-main/rtb_serial_robot-main/planar_3dof/xacro/lesson_urdf/meshes/visual/arm_link.stl" responded with 404: File not found)
    at Object.onError (index-0723cc3b940b78c7.js:194:104816)
    at index-0723cc3b940b78c7.js:186:224752
rU @ index-0723cc3b940b78c7.js:194
index-0723cc3b940b78c7.js:194  Error: Could not load retrieve/C:\Users\ningtianze\Desktop\rtb_serial_robot-main\rtb_serial_robot-main\planar_3dof\xacro\lesson_urdf\meshes\visual\gripper.stl: fetch for "http://localhost:52000/retrieve/C:/Users/ningtianze/Desktop/rtb_serial_robot-main/rtb_serial_robot-main/planar_3dof/xacro/lesson_urdf/meshes/visual/gripper.stl" responded with 404: File not found)
    at Object.onError (index-0723cc3b940b78c7.js:194:104816)
    at index-0723cc3b940b78c7.js:186:224752
rU @ index-0723cc3b940b78c7.js:194
framework-37f5df078e1d84d6.js:9  Error: Could not load retrieve/C:\Users\ningtianze\Desktop\rtb_serial_robot-main\rtb_serial_robot-main\planar_3dof\xacro\lesson_urdf\meshes\visual\gripper.stl: fetch for "http://localhost:52000/retrieve/C:/Users/ningtianze/Desktop/rtb_serial_robot-main/rtb_serial_robot-main/planar_3dof/xacro/lesson_urdf/meshes/visual/gripper.stl" responded with 404: File not found)
    at Object.onError (index-0723cc3b940b78c7.js:194:104816)
    at index-0723cc3b940b78c7.js:186:224752
a5 @ framework-37f5df078e1d84d6.js:9
main-b1241a9a70bb7dcd.js:1  Error: Could not load retrieve/C:\Users\ningtianze\Desktop\rtb_serial_robot-main\rtb_serial_robot-main\planar_3dof\xacro\lesson_urdf\meshes\visual\gripper.stl: fetch for "http://localhost:52000/retrieve/C:/Users/ningtianze/Desktop/rtb_serial_robot-main/rtb_serial_robot-main/planar_3dof/xacro/lesson_urdf/meshes/visual/gripper.stl" responded with 404: File not found)
    at Object.onError (index-0723cc3b940b78c7.js:194:104816)
    at index-0723cc3b940b78c7.js:186:224752
K @ main-b1241a9a70bb7dcd.js:1
main-b1241a9a70bb7dcd.js:1  A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K @ main-b1241a9a70bb7dcd.js:1
index-0723cc3b940b78c7.js:186 THREE.WebGLRenderer: Context Lost.

," which is consistent with what I encountered in my project. I am using a URDF file to describe a robot, and the robot's filename definition is relative to the root directory of the executing file, and tld is also correctly set. However, just like in your code, the model cannot be displayed correctly.   the stl file path is correct.

How can I resolve this? hope you can provide some ideas for fix this problems

thankyou

**Comment by olmerg** [comment]
Hello,

When I made this project the RTB had a issue to load the urdf from different locations, so I made the class [Planar3DOF](https://github.com/olmerg/rtb_serial_robot/blob/main/planar_3dof/Planar3DOF.py#L13)  which has a static function to load the path of the urdf. If you see the in the [robotic toolbox](https://github.com/petercorke/robotics-toolbox-python/blob/master/roboticstoolbox/models/URDF/Frankie.py#L35) it do not use the absolute path to load the urdf, so maybe you can try to remove the call to that static function.

I am not teaching this class this semester so I do not have an environment to test.

**Comment by ningmimg** [comment]
tks
